title: Christian Matt
description: Beratung, Workshops, Vorträge und Executive Education zu digitaler Transformation und verantwortungsvoller KI.
url: https://christianmatt.com
baseurl: ""
email: christian.matt@unibe.ch
phone: "+41 31 684 49 67"
linkedin: https://www.linkedin.com/in/christianmatt/
scholar: https://scholar.google.com/citations?user=HSsnJNgAAAAJ
researchgate: https://www.researchgate.net/profile/Christian-Matt

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
strict_front_matter: true
# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .idea
  - ebug
  - vendor
  - node_modules
